import 'package:alpha/models/model.dart';
import 'package:flutter/material.dart';

const Color kColor = Color(0xfffbf5f2);
const List<AlphaModel> alphaModelNumbersList = [
  AlphaModel(
    color: Color(0xFF2196F3),
    name: '1',
    letter: '',
    sound: 'assets/num_sounds/ar_one.mp3',
    alignment: Alignment.topLeft,
    image: 'assets/numbers/one.png',
  ),
  AlphaModel(
    color: Color(0xFFF44336),
    name: '2',
    letter: '',
    sound: 'assets/num_sounds/ar_two.mp3',
    alignment: Alignment.topCenter,
    image: 'assets/numbers/two.png',
  ),
  AlphaModel(
    color: Color(0xFF4CAF50),
    name: '3',
    letter: '',
    sound: 'assets/num_sounds/ar_three.mp3',
    alignment: Alignment.topRight,
    image: 'assets/numbers/three.png',
  ),
  AlphaModel(
    color: Color(0xFF9E9E9E),
    name: '4',
    letter: '',
    sound: 'assets/num_sounds/ar_four.mp3',
    alignment: Alignment.centerRight,
    image: 'assets/numbers/four.png',
  ),
  AlphaModel(
    color: Color(0xFFFFC107),
    name: '5',
    letter: '',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Color(0xFF9C27B0),
    name: '6',
    letter: '',
    sound: 'assets/num_sounds/ar_six.mp3',
    alignment: Alignment.centerLeft,
    image: 'assets/numbers/six.png',
  ),
  AlphaModel(
    color: Color(0xFF795548),
    name: '7',
    letter: '',
    sound: 'assets/num_sounds/ar_seven.mp3',
    alignment: Alignment.bottomLeft,
    image: 'assets/numbers/seven.png',
  ),
  AlphaModel(
    color: Color(0xFF2196F3),
    name: '8',
    letter: '',
    sound: 'assets/num_sounds/ar_eight.mp3',
    alignment: Alignment.bottomCenter,
    image: 'assets/numbers/eight.png',
  ),
  AlphaModel(
    color: Color(0xFFF44336),
    name: '9',
    letter: '',
    sound: 'assets/num_sounds/ar_nine.mp3',
    alignment: Alignment.bottomRight,
    image: 'assets/numbers/nine.png',
  ),
  AlphaModel(
    color: Color(0xFF4CAF50),
    name: '10',
    letter: '',
    sound: 'assets/num_sounds/ar_ten.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/ten.png',
  ),
];
const List<AlphaModel> alphaModelLettersList = [
  AlphaModel(
    color: Colors.blue,
    letter: 'أسد',
    name: 'أ',
    sound: 'assets/alef.mp3',
    alignment: Alignment.topLeft,
    image: 'assets/numbers/one.png',
  ),
  AlphaModel(
    color: Colors.red,
    letter: 'بطة',
    name: 'ب',
    sound: 'assets/num_sounds/ar_two.mp3',
    alignment: Alignment.topCenter,
    image: 'assets/numbers/two.png',
  ),
  AlphaModel(
    color: Colors.green,
    name: 'ت',
    letter: 'تفاحة',
    sound: 'assets/num_sounds/ar_three.mp3',
    alignment: Alignment.topRight,
    image: 'assets/numbers/three.png',
  ),
  AlphaModel(
    color: Colors.grey,
    name: 'ث',
    letter: 'ثعلب',
    sound: 'assets/num_sounds/ar_four.mp3',
    alignment: Alignment.centerRight,
    image: 'assets/numbers/four.png',
  ),
  AlphaModel(
    color: Colors.amber,
    name: 'ج',
    letter: 'جمل',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.purple,
    name: 'ح',
    letter: 'حصان',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.brown,
    name: 'خ',
    letter: 'خروف',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.blue,
    name: 'د',
    letter: 'ديك',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.red,
    name: 'ذ',
    letter: 'ذئب',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.green,
    name: 'ر',
    letter: 'رمان',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.grey,
    name: 'ز',
    letter: 'زرافة',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.amber,
    name: 'س',
    letter: 'سلحفاة',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.purple,
    name: 'ش',
    letter: 'شمس',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.orange,
    name: 'ص',
    letter: 'صاروخ',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.blue,
    name: 'ض',
    letter: 'ضفدع',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.red,
    name: 'ط',
    letter: 'طماطم',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.green,
    name: 'ظ',
    letter: 'ظبي',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.grey,
    name: 'ع',
    letter: 'عصفور',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.brown,
    name: 'غ',
    letter: 'غراب',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.purple,
    name: 'ف',
    letter: 'فيل',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.orange,
    name: 'ق',
    letter: 'قطة',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.blue,
    name: 'ك',
    letter: 'كلب',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.red,
    name: 'ل',
    letter: 'ليمون',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.green,
    name: 'م',
    letter: 'مروحة',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.grey,
    name: 'ن',
    letter: 'نملة',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.lime,
    name: 'هـ',
    letter: 'هدهد',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.purple,
    name: 'و',
    letter: 'وردة',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
  AlphaModel(
    color: Colors.orange,
    name: 'ي',
    letter: 'يد',
    sound: 'assets/num_sounds/ar_five.mp3',
    alignment: Alignment.center,
    image: 'assets/numbers/five.png',
  ),
];
